### ISSUE TITLE
libboost dependency missing

### ISSUE THREAD

**Issue by sam1013** [seL4/camkes-vm-manifest#1]
Hi!

I tried to fetch and build camkes-vm. I got an unresolved dependency to libboost. In special, "projects/vm/apps/vm/Kbuild:13" refers to libboost. Seems that libboost is missing in default.xml and working.xml manifest. 

Best, 
Sammey

**Comment by AdrianDanis** [comment]
The 'vm' application is bitrotted and is not meant to be used, the c162_twovm is currently the working one. Although 'working' here means it only runs on an AiTech C162. You can use `make  c162_twovm_defconfig` to configure this
